### ISSUE TITLE
python3.10 support

### ISSUE THREAD

**Issue by drgardner43** [pycontribs/jira#1293]
### Bug summary

Latest version of jira package from pypi doesn't work with python3.10

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Jira Instance type

Jira Server or Data Center (Self-hosted)

### jira-python version

3.1.1

### Python Interpreter version

3.10

### Which operating systems have you used?

- [X] Linux
- [ ] macOS
- [ ] Windows

### Reproduction steps

```python
Just try to:

from jira import JIRA
```

### Stack trace

```python
me@linux-host:/srv $ python3
Python 3.10.0 (default, Jan 13 2022, 23:17:28) [GCC 10.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from jira import JIRA
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'JIRA' from 'jira' (/opt/svl/lib/python3.10/site-packages/jira/__init__.py)
```

### Expected behaviour

import to work successfully, as it does with same version and python 3.8.5

### Additional Context

ipython==8.0.1

**Comment by adehad** [comment]
various dependencies have been updated to now support py3.10 so I would expect this to work now.

We will shortly be adding this to our pipeline (#1350)
