### ISSUE TITLE
Can pickle be used successful on jira v0.41 issue objects?

### ISSUE THREAD

**Issue by DanEhrlich** [pycontribs/jira#60]
I have not been able to get something like this to work.

issuses = jira.search_issues('project = "PROJECT" AND issuetype = "Some Issue Type"', maxResults=False)
with open('pickles.dat", 'w') as pickles:
    pickle.dump(issues, pickles,  pickle.HIGHEST_PROTOCOL)
issues2 = pickle.load(open('pickles.dat', 'r'))

The load fails with

AttributeError: <class 'jira.resources.Issue'> object has no attribute '_options'

Am I doing something wrong?  Or do these objects not work with pickle?

**Comment by lh84** [comment]
pickle works with version up to 0.32 and again from 0.43 (see https://github.com/pycontribs/jira/issues/46)

**Comment by DanEhrlich** [comment]
Thanks.  Of course, I have 0.41 installed.

**Comment by DanEhrlich** [comment]
OK.  I am confused.  I installed 0.47 and that caused requests to to updated to v2.6.1.  With this version of requests installed I get this when connecting to my jira instance:

/usr/lib/python2.6/site-packages/requests-2.6.1-py2.6.egg/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
Traceback (most recent call last):
  File "/usr/local/bin/drescripts/unitStatistics2.py", line 292, in <module>
    jira = util.connectToJira(jiraServer, jiraUser, jiraPass)
  File "/usr/local/bin/drescripts/utilities.py", line 135, in connectToJira
    jira = JIRA(options={'server': server}, basic_auth=(user, password), logging=debug)
  File "/usr/lib/python2.6/site-packages/jira/client.py", line 197, in __init__
    si = self.server_info()
  File "/usr/lib/python2.6/site-packages/jira/client.py", line 1368, in server_info
    return self._get_json('serverInfo')
  File "/usr/lib/python2.6/site-packages/jira/client.py", line 1764, in _get_json
    raise e
ValueError: No JSON object could be decoded

I backed off to requests-2.5.1 and things work again.  But, I also had to go back to the previous version of jira.  

Will this need for a true SSL Context object be addressed anytime soon?  I looked at the suggested url and the suggestion is to install Certify which requests is supposed to find and use if it is there.  But, I do not feel comfortable mucking around in client.py to try to make this work.

**Comment by ssbarnea** [comment]
I am not surprised about this as is caused by the security fixed made to Python and related libraries and the only good solution would be to upgrade your python version. 

Sorry but we cannot afford to support unsupported versions of Python. If there is no workaround I will officially remove old python versions from the list.

**Comment by DanEhrlich** [comment]
RHEL 6.6 comes with Python 2.6.6 and that is what I have to use.  Having a parralell python 2.7 or 3.4 install would be an support nightmare as I do not have enough cycles now to do what is asked of me.

I guess I will stick with what is installed until RedHat gets on the stick and updates python and the libraries.

Thanks for the help.

**Comment by DanEhrlich** [comment]
We can close this.

**Comment by ssbarnea** [comment]
Here is a hint: try to use the alternative python version and you should have less issues. Even py34 should work well.

Sorry but the recent SSL issues are affecting all of us.
